apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-greetingsapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-greetings
      version: blue
  template:
    metadata:
      name: web-greetingsapp-pod
      labels:
        app: app-greetings
        version: blue
    spec:
      containers:
      - name: web-greetingsapp-container
        image: gcr.io/project-everis/apps-restapi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-greetings-svc
  labels:
    app: app-greetings
spec:
  selector:
    app: app-greetings
    version: blue
  type: NodePort
  ports:
  - nodePort: 31120
    port: 5000
    targetPort: 5000
